# Generated by Django 5.2.3 on 2025-06-27 12:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
                ('ConsultationFees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('LabTestId', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=200)),
                ('TestDescription', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('MedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('Address', models.TextField()),
                ('Gender', models.CharField(max_length=10)),
                ('BloodGroup', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('ReceptionistId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('BloodGroup', models.CharField(max_length=5)),
                ('Salary', models.IntegerField()),
                ('DateOfJoining', models.DateField()),
                ('Qualifications', models.CharField(max_length=100)),
                ('Availablility', models.BooleanField(default=True)),
                ('DeptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentDate', models.DateField()),
                ('AppointmentTime', models.TimeField(choices=[(datetime.time(10, 0), '10:00 AM'), (datetime.time(10, 30), '10:30 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 30), '01:30 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(14, 30), '02:30 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(15, 30), '03:30 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(16, 30), '04:30 PM'), (datetime.time(17, 0), '05:00 PM')])),
                ('Status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.doctor')),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateIssued', models.DateField()),
                ('Description', models.CharField(max_length=200)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.appointment')),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.doctor')),
                ('LabTestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.labtest')),
                ('MedicineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('DoctorId', 'AppointmentDate', 'AppointmentTime'), name='unique_doctor_date_time'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('PatientId', 'AppointmentDate', 'AppointmentTime'), name='unique_patient_date_time'),
        ),
    ]
